### PR TITLE
Redesigned B8 stick device code.

### PR DESCRIPTION
**Pull request by pfueyor**
This pull request redesigns completely the code of the B8 stick,
introducing the following changes:

- Define names for the pin numbers where each button is connected.

- Give meaning variable names to x and y values, in order to better
  document which is the axis of the pot that is read.

- Avoid iterating over all the button pins with a for loop to set
  the pins as input pullup. As all the buttons are connected to
  Arduino's digital pins 2 to 7, it means that they are connected
  to pins 2 to 7 of port D of the AVR microcontroller. Thus,
  instead of iterating, all the pin modes can be set with
  two single instructions.

- Following the previous point, all the button pins can be read
  with a single line of code, reading directly the PIND register.
  This is critical to reduce the latency of the device.

- Remove unneeded global variables.

- Format and document the code to improve readability

### CODE REVIEW

**Comment by pfueyor** [comment]
I can't test the code with a physical real device. Please, test it before merge.

**Review by hc625ma — COMMENTED** [review]
I have made a few changes, please look at the code, if it's fine, I will put my stick back together and merge it=)

**Comment by pfueyor** [comment]
Generally I agree, but I would suggest some changes:

- Lines 47 and 136 are wrong. It should be #if defined(GRIP_TEST) instead of #if (defined GRIP_TEST)

- Line 67: take into account that you are configuring pin 1 as input. If you uncomment the GRIP_TEST macro and want to receive data via Serial, the Serial communications in Arduino use pins 0 and 1 for RX and TX purposes. So there shouldn't be anything connected to pins 0 and 1 if Serial communication is intended to be used. That's why I left pin 1 unchanged with DDRD &= ~0b11111100.

- Line 92: I think that the variable 'buf' and assigning it to 'buttons' value is not needed. The previous line reads all inputs at once into 'buttons'. After that, you can safely make whatever changes you want into that variable, because it won't be changed until loop() finishes. You can simply read 'buttons' and the apply your logic to change the individual pins of 'buttons'. 

- I don't assign '0' or '1' to boolean variables. I instead assign 'false' or 'true'. Assigning numerical values explicity to boolean variables takes to confussion.

**Comment by hc625ma** [comment]
hmm about the "buf", I think it's needed, as we need to differentiate physical button presses and logical ones. The intercom button should only be pressed when we hold it for a certain timeout, because physically, when you press the PTT button, you also press the INTERCOM button =) 

So, basically, its press half-ways and hold for IC, and full-press for PTT. When you release PTT, IC or PTT buttons won't be pressed anymore until you release the IC as well.

With this in mind, the PTT button should be set to off right after we read buttons (we don't want an interrupt to happen in between!) But then, how do we know if the button is pressed? That's why.

**Comment by hc625ma** [comment]
fixed other stuff =) I thought that pin might have been affecting button 4 that didn't work (2 AM lol). Found out it was a cut wire. Will have to fix that thing in the model as well =)

What do you think, is it good enough now?

**Pull request merged**
